config/routes.rb
Rails.application.routes.draw do

  get 'tweets/show'

  resources :twitter_trucks
  resources :tweets
  resources :coordinates

  root 'twitter_trucks#index'
  

  
  
end

app/models/twitter_truck.rb
class TwitterTruck < ActiveRecord::Base
  include TwitterAccessor
  
  @@last_updated = nil
  
  def self.update_trucks
    if @@last_updated.nil? || (Time.now - @@last_updated) > (60 * 60)
      @@last_updated = Time.now      

      trucks = get_list_members

      trucks.each do |truck|
        truck_id = truck.id
        twitter_trucks = TwitterTruck.where("twitter_user_id = #{truck_id}")
        twitter_truck = twitter_trucks[0]
        
        if twitter_truck.nil?
          twitter_truck = TwitterTruck.new
          twitter_truck.twitter_user_id = truck.id
        end

        twitter_truck.name = truck.name
        twitter_truck.twitter_screen_name = truck.screen_name
        twitter_truck.image_url = truck.profile_image_url(size = :normal).to_s
        twitter_truck.save
      end
    end

    return trucks
  end
  
  def get_timeline_since(date)
    get_timeline_for_user_since(self.twitter_user_id,date)
  end

end

app/controllers/twitter_trucks_controller.rb
class TwitterTrucksController < ApplicationController
  before_action :set_twitter_truck, only: [:show, :edit, :update, :destroy]

  # GET /twitter_trucks
  # GET /twitter_trucks.json
  def index
    TwitterTruck.update_trucks
    Tweet.update_tweets
    
    @truck_tweets = Hash.new
    current_date = DateTime.now.in_time_zone("EST").beginning_of_day
    
    tweets = Tweet.where("tweet_created_at >= '#{current_date.to_s}'").order(tweet_created_at: :desc)
    
    tweets.each { |tweet| @truck_tweets[tweet.twitter_user_id] = tweet if !@truck_tweets[tweet.twitter_user_id] && tweet.contains_address? && !tweet.get_coordinate.latitude.nil?}
    
    @trucks_without_location = []
    @all_trucks = Hash.new
    
    TwitterTruck.all.each do |truck|
      @all_trucks[truck.twitter_user_id] = truck
      @trucks_without_location << truck if @truck_tweets[truck.twitter_user_id].nil?
    end
    
    @hash = Gmaps4rails.build_markers(@truck_tweets.values) do |tweet, marker|
      coordinates = tweet.get_coordinate
      #sleep(1.0/8.0) #/
      
      #unless coordinates[0].nil? || coordinates[1].nil?
      marker.lat coordinates.latitude
      marker.lng coordinates.longitude
      marker.infowindow render_to_string(:partial => "/twitter_trucks/infowindow", :locals => { :tweet => tweet})
      marker.picture({
                     "url" => @all_trucks[tweet.twitter_user_id].image_url,
                     "width" =>  40,
                     "height" => 40})
      #end
    end
  end

  # GET /twitter_trucks/1
  # GET /twitter_trucks/1.json
  def show
    @truck = TwitterTruck.find(params[:id])
    @truck_tweets = Tweet.where(twitter_user_id: @truck.twitter_user_id).order(tweet_created_at: :desc)
    @location_tweets = @truck_tweets.select do |tweet| tweet.contains_address? end
    @bad_coordinate_tweets = @location_tweets.select do |tweet| tweet.get_coordinate.latitude.nil? end
    
    @hash = Gmaps4rails.build_markers(@location_tweets) do |tweet, marker|
      coordinates = tweet.get_coordinate
      marker.lat coordinates.latitude
      marker.lng coordinates.longitude
      marker.infowindow render_to_string(:partial => "/tweets/infowindow", :locals => { :tweet => tweet})
    end
  end

  # GET /twitter_trucks/new
  def new
    @twitter_truck = TwitterTruck.new
  end

  # GET /twitter_trucks/1/edit
  def edit
  end

  # POST /twitter_trucks
  # POST /twitter_trucks.json
  def create
    @twitter_truck = TwitterTruck.new(twitter_truck_params)

    respond_to do |format|
      if @twitter_truck.save
        format.html { redirect_to @twitter_truck, notice: 'Twitter truck was successfully created.' }
        format.json { render :show, status: :created, location: @twitter_truck }
      else
        format.html { render :new }
        format.json { render json: @twitter_truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twitter_trucks/1
  # PATCH/PUT /twitter_trucks/1.json
  def update
    respond_to do |format|
      if @twitter_truck.update(twitter_truck_params)
        format.html { redirect_to @twitter_truck, notice: 'Twitter truck was successfully updated.' }
        format.json { render :show, status: :ok, location: @twitter_truck }
      else
        format.html { render :edit }
        format.json { render json: @twitter_truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twitter_trucks/1
  # DELETE /twitter_trucks/1.json
  def destroy
    @twitter_truck.destroy
    respond_to do |format|
      format.html { redirect_to twitter_trucks_url, notice: 'Twitter truck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twitter_truck
      @twitter_truck = TwitterTruck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def twitter_truck_params
      params.require(:twitter_truck).permit(:twitter_user_id, :name, :image_url)
    end
end

app/helpers/twitter_trucks_helper.rb
module TwitterTrucksHelper
end

app/views/twitter_trucks/_form.html.erb
<%= form_for(@twitter_truck) do |f| %>
  <% if @twitter_truck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@twitter_truck.errors.count, "error") %> prohibited this twitter_truck from being saved:</h2>

      <ul>
      <% @twitter_truck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :twitter_user_id %><br>
    <%= f.number_field :twitter_user_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :twitter_screen_name %><br>
    <%= f.text_field :twitter_screen_name %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/twitter_trucks/_infowindow.html.erb
<h1><%= @all_trucks[tweet.twitter_user_id].name %></h1>
<h2><%= tweet.text %></h2>
<h3><%= tweet.tweet_created_at.to_s.in_time_zone("EST") %></h3>
<h3><%= tweet.clean_text_for_regex %></h3>
<h3><%= tweet.extract_address << ", " << tweet.extract_city %></h3>
<%= link_to "Show", @all_trucks[tweet.twitter_user_id] %> <%= link_to "Show Tweet", tweet %>

app/views/twitter_trucks/edit.html.erb
<h1>Editing twitter_truck</h1>

<%= render 'form' %>

<%= link_to 'Show', @twitter_truck %> |
<%= link_to 'Back', twitter_trucks_path %>

app/views/twitter_trucks/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", '#', id: "logo" %>
    </div>
  </div>
</header>

<div>
  <div id="map"></div>
    <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#heardFrom">
      Heard From Today
    </button>
    <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#notHeardFrom">
      Not Heard From Today
    </button>
</div>

<script type='text/javascript'>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    if(navigator.geolocation);
      navigator.geolocation.getCurrentPosition(displayOnMap);
  
  function displayOnMap(position){
    var marker = handler.addMarker({
      lat: position.coords.latitude,
      lng: position.coords.longitude
    });
    handler.map.centerOn(marker);
  };
});
</script>

<div class="modal fade" id="heardFrom" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Not Heard From Today</h4>
      </div>
      <div class="modal-body">
        <ul>
          <% @truck_tweets.values.each do |tweet| %>
          <li><%= @all_trucks[tweet.twitter_user_id].name %> <%= tweet.text %> <%= tweet.extract_address %> <%= tweet.get_coordinate.latitude.nil? %></li>
            <% end %>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="notHeardFrom" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Not Heard From Today</h4>
      </div>
      <div class="modal-body">
        <ul>
            <% @trucks_without_location.each do |truck| %>
              <li><%= image_tag(truck.image_url) %>  <%= link_to truck.name, truck %></li>
            <% end %>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/twitter_trucks/new.html.erb
<h1>New twitter_truck</h1>

<%= render 'form' %>

<%= link_to 'Back', twitter_trucks_path %>

app/views/twitter_trucks/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=visualization"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<p id="notice"><%= notice %></p>

<p>
  <strong>Twitter user:</strong>
  <%= @twitter_truck.twitter_user_id %>
</p>

<p>
  <strong>User name:</strong>
  <%= @twitter_truck.name %>
</p>


<div style='width: 800px;'>
  <div id ="panel">
    <button onclick="hideMarkers()">Hide Markers</button>
  </div>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<h2>Bad Coordinates</h2>
<table>
  <tbody>
    <% @bad_coordinate_tweets.each do |tweet| %>
      <tr>
        <td><%= link_to tweet.text, tweet %></td>
        <td><%= tweet.tweet_created_at %></td>
        <td><%= tweet.contains_address? %></td>
        <td><%= tweet.clean_text_for_regex %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>All Tweets</h2>
<table>
  <tbody>
    <% @truck_tweets.each do |tweet| %>
      <tr>
        <td><%= link_to tweet.text, tweet %></td>
        <td><%= tweet.tweet_created_at %></td>
        <td><%= tweet.contains_address? %></td>
        <td><%= tweet.clean_text_for_regex %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<script type='text/javascript'>
  var markers = []
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
  
  var data = <%=raw @hash.to_json %>;
  var heatMapData = []

  for(var i = 0; i < data.length; i++) {
    heatMapData.push(new google.maps.LatLng(data[i].lat, data[i].lng));
  }

  var pointArray = new google.maps.MVCArray(heatMapData);
  
  var heatmap = new google.maps.visualization.HeatmapLayer({
    data: pointArray
  })
  
  heatmap.setMap(handler.getMap());
  heatmap.set('radius',20);
  
  function hideMarkers(){
    handler.removeMarkers(markers)
  }
</script>

<%= link_to 'Back', twitter_trucks_path %>