config/routes.rb
Rails.application.routes.draw do

  get 'tweets/show'

  resources :twitter_trucks
  resources :tweets
  resources :coordinates

  root 'twitter_trucks#index'
  

  
  
end

app/models/coordinate.rb
class Coordinate < ActiveRecord::Base
  validates_uniqueness_of :address
  include RegexpBuilder
  
  @@all_coordinates = nil
  
  def self.find_coordinate(address)
    if @@all_coordinates.nil?
      @@all_coordinates = Hash.new
      Coordinate.all.each { |c| @@all_coordinates[c.address] = c }
    end
    
    coordiante = @@all_coordinates[address]
    
    if coordiante.nil?
      coordinate = Coordinate.new
      coordinate.address = address
      coordinate.geocode_address
      coordinate.save
      @@all_coordinates[address] = coordinate
      return coordinate
    end
    
    return coordiante
  end
  
  def clean_address_for_geocoder
    clean_address = self.address.delete("!")

    clean_address = clean_address.gsub("&"," and ")
    clean_address = clean_address.gsub("@"," and ")
    
    clean_address = clean_address.gsub("/"," and ")
    clean_address = clean_address.gsub("\\"," and ")
    
    clean_address = clean_address.gsub(/(?<=[0-9])av/i,' av')
    clean_address = clean_address.gsub(/(?<=[2-90])st/i,' st')
    
    clean_address = clean_address.gsub(/(?<=11)\s/i,'th ')
    clean_address = clean_address.gsub(/(?<=12)\s/i,'th ')
    clean_address = clean_address.gsub(/(?<=13)\s/i,'th ')
    clean_address = clean_address.gsub(/(?<=1)\s/i,'st ')
    clean_address = clean_address.gsub(/(?<=2)\s/i,'nd ')
    clean_address = clean_address.gsub(/(?<=3)\s/i,'rd ')
    clean_address = clean_address.gsub(/(?<=(4|5|6|7|8|9|0))\s/i,'th ')
    
    clean_address = clean_address.strip
    return clean_address.squeeze(" ")
  end
  
  def geocode_address
    clean_address = clean_address_for_geocoder
    return if clean_address.length == 0
    address = clean_address.partition(/,[^,]+,\s\S{2}\z/i) [0]
    city_state = clean_address.match(/[^,]+,\s\S{2}\z/i) [0].strip!

    bounds = []
    
    case city_state
    when "New York, NY"
      bounds = [[40.709503,-73.971634],[40.765782,-74.021072]]
    when "Brooklyn, NY"
      bounds = [[40.556714,-73.811989],[40.743217,-74.068108]]
    when "Queens, NY"
      bounds = [[40.546279,-73.665047],[40.804056,-73.998756]]      
    end
    
    unless get_regexp(include_between).match(address).nil? || !get_regexp(street_address).match(address).nil?
      first_street = get_regexp(between_address_first_part).match(address)
      intersection_text = get_regexp(intersection).match(address)
      unless intersection_text.nil? 
        first_cross_street = get_regexp(intersection_first_street).match(intersection_text[0])
        second_cross_street = get_regexp(intersection_second_street).match(intersection_text[0])
      end
      
      return if first_street.nil? || first_cross_street.nil? || second_cross_street.nil?
      
      first_intersection = first_street[0] + " and " + first_cross_street[0] + ", " + city_state
      second_intersection = first_street[0] + " and " + second_cross_street[0] + ", " + city_state

      first_geocode = Geocoder.search(first_intersection, :bounds => bounds)
      second_geocode = Geocoder.search(second_intersection, :bounds => bounds)
      
      unless first_geocode[0].nil? || second_geocode[0].nil?
        self.latitude = (first_geocode[0].coordinates()[0] + second_geocode[0].coordinates()[0])/2 #/
        self.longitude = (first_geocode[0].coordinates()[1] + second_geocode[0].coordinates()[1])/2 #/
      end
    else
      geocode = Geocoder.search(clean_address_for_geocoder, :bounds => bounds)
      
      unless geocode[0].nil? 
        self.latitude = geocode[0].coordinates()[0]
        self.longitude = geocode[0].coordinates()[1]
      end
    end
    
  end
end

app/controllers/coordinates_controller.rb
class CoordinatesController < ApplicationController
  before_action :set_coordinate, only: [:show, :edit, :update, :destroy]
  
  def index
    @coordinates = Coordinate.all
  end

  def show
    coordinate = Coordinate.find(params[:id])
    
    @hash = Gmaps4rails.build_markers(coordinate) do |past_location, marker|
      marker.lat coordinate.latitude
      marker.lng coordinate.longitude
    end
  end

  def new
    @coordinate = Coordinate.new
  end

  def edit
    @coordinate.geocode_address
  end

  def create
    @coordinate = Coordinate.new(coordinate_params)

    respond_to do |format|
      if @coordinate.save
        format.html { redirect_to @coordinate, notice: 'coordinate was successfully created.' }
        format.json { render :show, status: :created, location: @coordinate }
      else
        format.html { render :new }
        format.json { render json: @coordinate.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @coordinate.update(coordinate_params)
        format.html { redirect_to @coordinate, notice: 'coordinate was successfully updated.' }
        format.json { render :show, status: :ok, location: @coordinate }
      else
        format.html { render :edit }
        format.json { render json: @coordinate.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @coordinate.destroy
    respond_to do |format|
      format.html { redirect_to coordinates_url, notice: 'coordinate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coordinate
      @coordinate = Coordinate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coordinate_params
      params.require(:coordinate).permit(:address, :latitude, :longitude)
    end
end

app/helpers/coordinate_helper.rb
module CoordinateHelper
end

app/views/coordinates/_form.html.erb
<%= form_for(@coordinate) do |f| %>
  <% if @coordinate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coordinate.errors.count, "error") %> prohibited this coordinate from being saved:</h2>

      <ul>
      <% @coordinate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coordinates/create.html.erb
<h1>Coordinate#create</h1>
<p>Find me in app/views/coordinate/create.html.erb</p>

app/views/coordinates/destroy.html.erb
<h1>Coordinate#destroy</h1>
<p>Find me in app/views/coordinate/destroy.html.erb</p>

app/views/coordinates/edit.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>


<h1>Editing coordinate</h1>
<h3><%= @coordinate.address %></h3>
<h3><%= @coordinate.clean_address_for_geocoder %></h3>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<%= render 'form' %>

<script type='text/javascript'>

  handler = Gmaps.build('Google');
  var marker = null;
  
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){  
    marker = handler.addMarker({
        lat: <%=raw @coordinate.latitude %>,
        lng: <%=raw @coordinate.longitude %>
    });  
    handler.map.centerOn(marker);
  });
  
  
  google.maps.event.addListener(handler.getMap(), 'dblclick', function(e) {
    var myLatLng = e.latLng;
    
    handler.removeMarker(marker);
    marker = handler.addMarker({lat: myLatLng.lat(), lng: myLatLng.lng()});
    
    document.getElementById("coordinate_latitude").value = myLatLng.lat();
    document.getElementById("coordinate_longitude").value = myLatLng.lng();
  });
  
  handler.getMap().setZoom(15);

</script>

<%= link_to 'Show', @coordinate %> |
<%= link_to 'Back', coordinates_path %>

app/views/coordinates/index.html.erb
<h1>Saved Coordinates</h1>
<%= link_to 'Back to Trucks', root_path %>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coordinates.each do |coordinate| %>
      <tr>
        <td><%= coordinate.address %></td>
        <td><%= coordinate.latitude %></td>
        <td><%= coordinate.longitude %></td>
        <td><%= link_to 'Show', coordinate %></td>
        <td><%= link_to 'Edit', edit_coordinate_path(coordinate) %></td>
        <td><%= link_to 'Destroy', coordinate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/coordinates/new.html.erb
<h1>Coordinate#new</h1>
<p>Find me in app/views/coordinate/new.html.erb</p>

app/views/coordinates/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<p>
  <strong>Address:</strong>
  <%= @coordinate.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @coordinate.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @coordinate.longitude %>
</p>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type='text/javascript'>

  handler = Gmaps.build('Google');

  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){  
    var marker = handler.addMarker({
        lat: <%=raw @coordinate.latitude %>,
        lng: <%=raw @coordinate.longitude %>
    });  
    handler.map.centerOn(marker);
  });
  
  handler.getMap().setZoom(15);
 
  
</script>

<%= link_to 'Edit', edit_coordinate_path(@coordinate) %> |
<%= link_to 'Destroy', @coordinate, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', coordinates_path %>

app/views/coordinates/update.html.erb
<h1>Coordinate#update</h1>
<p>Find me in app/views/coordinate/update.html.erb</p>